version: '3.2'
services:
  dbbrowser:
    container_name: dbbrowser
    image: arthurlehdermann/ubuntu-apache-php
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
